spring:
  datasource:
    # DB 접속 URL 설정 (MariaDB 사용)
    # 운영 서버 DB 연결
#    url: jdbc:mariadb://rapportcompany.cafe24.com:3306/rapportcompany?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true

    # 로컬 개발용 DB 연결 (주석 처리됨)
    url: jdbc:mariadb://localhost:3306/rapportcompany?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true

    # JDBC 드라이버 클래스명
    driver-class-name: org.mariadb.jdbc.Driver

    # DB 접속 계정 정보
    # username: root
    # password: 1234
    username: rapportcompany
    password: Ksh-8818510

  jpa:
    hibernate:
      ddl-auto: none  # 스키마 자동 생성/수정 비활성화 (none: 변경하지 않음)
      naming:
        # DB 필드명을 camelCase로 매핑하지 않고 그대로 사용 (예: user_name → user_name)
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        format_sql: true         # SQL 보기 좋게 포맷팅
        highlight_sql: true      # SQL 하이라이트 적용 (Spring Boot 3.x+)
        use_sql_comments: true   # SQL 실행 시 주석 표시

logging:
  level:
    # 패키지별 로그 레벨 설정 (error, info, debug 등)
    com.project.place.config: error
    org.thymeleaf: error

    # Hibernate가 실행하는 SQL 로그 출력
    org.hibernate.SQL: debug
    # SQL 파라미터 바인딩 값까지 추적 로그 출력
    org.hibernate.type.descriptor.sql: trace

decorator:
  thymeleaf:
    cache: false        # HTML 변경 시 바로 반영되도록 캐시 비활성화
    mode: HTML          # Thymeleaf HTML 모드 사용
    encoding: UTF-8     # 템플릿 파일 인코딩
    prefix: classpath:/templates/  # 템플릿 파일 위치
    suffix: .html       # 템플릿 파일 확장자

server:
  port: 80              # 웹 서버 포트 설정 (기본: 8080 → 80으로 변경)
  servlet:
    session:
      timeout: 1800s   # 세션 타임아웃 시간 (30분)
  error:
    whitelabel:
      enabled: false    # Spring 기본 Whitelabel 에러 페이지 비활성화
  forward-headers-strategy: native  # 프록시 환경에서 헤더 처리 방식 설정
